---
name: 'Setup Kitten'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Kitten.'
branding:
  icon: terminal
  color: gray-dark
runs:
  using: 'composite'
  steps:
    - name: Define vars
      id: vars
      run: |
        mkdir -p "$RUNNER_TEMP/kitten"
        echo "KITTEN_PATH=$RUNNER_TEMP/kitten" >> $GITHUB_OUTPUT
      shell: bash
    - name: Clone Kitten repository
      env:
        KITTEN_VERSION: a5301fe24dbb9ea91974abee73ad544156ee4722 # pragma: allowlist secret
      run: |
        git clone https://github.com/evincarofautumn/kitten.git "${{ steps.vars.outputs.KITTEN_PATH }}"
        git reset --hard $KITTEN_VERSION
      shell: bash
      working-directory: ${{ steps.vars.outputs.KITTEN_PATH }}
    - name: Build Kitten
      run: |
        stack setup --stack-yaml stack.yaml
        stack build --stack-yaml stack.yaml
      shell: bash
      working-directory: ${{ steps.vars.outputs.KITTEN_PATH }}
    - name: Add Kitten to PATH
      run: |
        p=$(find "${{ steps.vars.outputs.KITTEN_PATH }}/.stack-work/install" -name "kitten*")
        echo "Executable file has been found at $p"
        bin_path=$(dirname $p)
        echo "Parent folder of Executable file is $bin_path"
        echo "$bin_path" >> $GITHUB_PATH
      shell: bash
