---
name: 'Setup Kitten'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Kitten.'
branding:
  icon: terminal
  color: gray-dark
runs:
  using: 'composite'
  steps:
    - name: Setup Kitten
      run: |
        kitten_path="$HOME/.local/bin/kitten"
        mkdir -p $kitten_path
        git clone https://github.com/evincarofautumn/kitten.git $kitten_path
        stack setup --stack-yaml $kitten_path/stack.yaml
        stack build --stack-yaml $kitten_path/stack.yaml
        echo "$kitten_path/.stack-work/install" >> $GITHUB_PATH
      shell: bash
