---
name: 'Setup Kitten'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Kitten.'
branding:
  icon: terminal
  color: gray-dark
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      name: Cache ~/.stack
      if: ${{ runner.os != 'Windows' }}
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-global-
    - uses: actions/cache@v3
      name: Cache .stack-work
      if: ${{ runner.os != 'Windows' }}
      with:
        path: ${{ env.HOME }}/.local/bin/kitten/.stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-
    - uses: actions/cache@v3
      name: Cache %APPDATA%\stack %LOCALAPPDATA%\Programs\stack
      if: ${{ runner.os == 'Windows' }}
      with:
        path: |
          ~\AppData\Roaming\stack
          ~\AppData\Local\Programs\stack
        key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-global-
    - uses: actions/cache@v3
      name: Cache .stack-work
      if: ${{ runner.os == 'Windows' }}
      with:
        path: ${{ env.HOME }}/.local/bin/kitten/.stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-
    - name: Build Kitten
      run: |
        kitten_path="$HOME/.local/bin/kitten"
        mkdir -p $kitten_path
        git clone https://github.com/evincarofautumn/kitten.git $kitten_path
        stack setup --stack-yaml $kitten_path/stack.yaml
        stack build --stack-yaml $kitten_path/stack.yaml
      shell: bash
    - name: Add Kitten to PATH (Linux, macOS)
      if: ${{ runner.os != 'Windows' }}
      run: echo "$(find $HOME/.local/bin/kitten/.stack-work/install -name "kitten*" | xargs dirname)" >> $GITHUB_PATH
      shell: bash
    - name: Add Kitten to PATH (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: Get-ChildItem -Path $env:HOME\.local\bin\kitten\.stack-work\install -Filter kitten.exe -Recurse -ErrorAction SilentlyContinue -Force | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
