---
name: 'Setup Kitten'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Kitten.'
branding:
  icon: terminal
  color: gray-dark
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          KITTEN_EXEC_NAME=kitten.exe
          STACK_EXEC_NAME=stack.exe
          BINARY_NAME=windows
        else
          KITTEN_EXEC_NAME=kitten
          STACK_EXEC_NAME=stack
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            BINARY_NAME=linux
          else
            BINARY_NAME=osx
          fi
        fi
        echo "KITTEN_EXEC_NAME=$KITTEN_EXEC_NAME" >> $GITHUB_OUTPUT
        echo "STACK_EXEC_NAME=$STACK_EXEC_NAME" >> $GITHUB_OUTPUT
        echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_OUTPUT
        KITTEN_INSTALLED=$(if command -v $CLI_NAME >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "KITTEN_INSTALLED=$KITTEN_INSTALLED" >> $GITHUB_OUTPUT
        STACK_INSTALLED=$(if command -v stack >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "STACK_INSTALLED=$STACK_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$RUNNER_TEMP/kitten"
        echo "KITTEN_PATH=$RUNNER_TEMP/kitten" >> $GITHUB_OUTPUT
        mkdir -p "$RUNNER_TEMP/stack"
        echo "STACK_PATH=$RUNNER_TEMP/stack" >> $GITHUB_OUTPUT
      shell: bash
    - name: Setup Stack
      if: ${{ steps.info.outputs.STACK_INSTALLED == 'false' && runner.os != 'Windows' }}
      run: |
        wget -c https://get.haskellstack.org/stable/${{ steps.info.outputs.BINARY_NAME }}-x86_64.tar.gz -O - | tar -xz
        ls -A ./stack-2.9.1-linux-x86_64
        exe_path=$(find . -name "${{ steps.info.outputs.STACK_EXEC_NAME }}")
        echo "exe_path :: $exe_path"
        stack_path=$(dirname "$exe_path")
        chmod +x "exe_path"
        echo "$stack_path" >> $GITHUB_PATH
      shell: bash
      working-directory: ${{ steps.info.outputs.STACK_PATH }}
    - name: Clone Kitten repository
      if: ${{ steps.info.outputs.KITTEN_INSTALLED == 'false' }}
      env:
        KITTEN_VERSION: a5301fe24dbb9ea91974abee73ad544156ee4722 # pragma: allowlist secret
      run: |
        git clone https://github.com/evincarofautumn/kitten.git "${{ steps.info.outputs.KITTEN_PATH }}"
        git reset --hard $KITTEN_VERSION
      shell: bash
      working-directory: ${{ steps.info.outputs.KITTEN_PATH }}
    - name: Build Kitten
      if: ${{ steps.info.outputs.KITTEN_INSTALLED == 'false' }}
      run: |
        stack setup --stack-yaml stack.yaml
        stack build --stack-yaml stack.yaml
      shell: bash
      working-directory: ${{ steps.info.outputs.KITTEN_PATH }}
    - name: Add Kitten to PATH
      if: ${{ steps.info.outputs.KITTEN_INSTALLED == 'false' }}
      run: |
        exe_path=$(find "${{ steps.info.outputs.KITTEN_PATH }}/.stack-work/install" -name "${{ steps.info.outputs.KITTEN_EXEC_NAME }}")
        bin_path=$(dirname $exe_path)
        echo "$bin_path" >> $GITHUB_PATH
      shell: bash
