---
name: 'Setup Kitten'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Kitten.'
branding:
  icon: terminal
  color: gray-dark
runs:
  using: 'composite'
  steps:
    - name: Define vars
      id: vars
      run: |
        mkdir -p $RUNNER_TEMP/kitten
        echo "KITTEN_PATH=$RUNNER_TEMP/kitten" >> $GITHUB_OUTPUT
      shell: bash
    - name: Clone Kitten repository
      env:
        KITTEN_VERSION: a5301fe24dbb9ea91974abee73ad544156ee4722 # pragma: allowlist secret
      run: |
        git clone https://github.com/evincarofautumn/kitten.git ${{ steps.vars.outputs.KITTEN_PATH }}
        git reset --hard $KITTEN_VERSION
      shell: bash
      working-directory: ${{ steps.vars.outputs.KITTEN_PATH }}
    - name: Cache .stack-work
      uses: actions/cache@v3
      id: cache-stack-work
      with:
        path: ${{ steps.vars.outputs.KITTEN_PATH }}/.stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('${{ steps.vars.outputs.KITTEN_PATH }}/stack.yaml') }}-${{ hashFiles('${{ steps.vars.outputs.KITTEN_PATH }}/**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-
    - name: Build Kitten
      if: ${{ steps.cache-stack-work.outputs.cache-hit != 'true' }}
      run: |
        stack setup --stack-yaml stack.yaml
        stack build --stack-yaml stack.yaml
      shell: bash
      working-directory: ${{ steps.vars.outputs.KITTEN_PATH }}
    - name: Add Kitten to PATH
      run: echo "$(find ${{ steps.vars.outputs.KITTEN_PATH }}/.stack-work/install -name "kitten*" | xargs dirname)" >> $GITHUB_PATH
      shell: bash
