---
name: 'Setup Kitten'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Kitten.'
branding:
  icon: terminal
  color: gray-dark
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        KITTEN_EXEC_NAME=kitten
        if [ "${{ runner.os }}" = "Windows" ]; then
          KITTEN_EXEC_NAME="$KITTEN_EXEC_NAME.exe"
        fi
        echo "KITTEN_EXEC_NAME=$KITTEN_EXEC_NAME" >> $GITHUB_OUTPUT
        KITTEN_INSTALLED=$(if command -v $KITTEN_EXEC_NAME >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "KITTEN_INSTALLED=$KITTEN_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$RUNNER_TEMP/kitten"
        echo "KITTEN_PATH=$RUNNER_TEMP/kitten" >> $GITHUB_OUTPUT
      shell: sh
    - name: Clone Kitten repository
      if: ${{ steps.info.outputs.KITTEN_INSTALLED == 'false' }}
      env:
        KITTEN_VERSION: a5301fe24dbb9ea91974abee73ad544156ee4722 # pragma: allowlist secret
      run: |
        git clone https://github.com/evincarofautumn/kitten.git "${{ steps.info.outputs.KITTEN_PATH }}"
        git reset --hard $KITTEN_VERSION
        yq e -i '.resolver = "lts-19.17"' stack.yaml
      shell: sh
      working-directory: ${{ steps.info.outputs.KITTEN_PATH }}
    - name: Build Kitten
      if: ${{ steps.info.outputs.KITTEN_INSTALLED == 'false' }}
      run: |
        cat stack.yaml
        stack setup --stack-yaml stack.yaml
        stack build --stack-yaml stack.yaml
      shell: sh
      working-directory: ${{ steps.info.outputs.KITTEN_PATH }}
    - name: Add Kitten to PATH
      if: ${{ steps.info.outputs.KITTEN_INSTALLED == 'false' }}
      run: |
        exe_path=$(find "${{ steps.info.outputs.KITTEN_PATH }}/.stack-work/install" -name "${{ steps.info.outputs.KITTEN_EXEC_NAME }}")
        bin_path=$(dirname $exe_path)
        echo "$bin_path" >> $GITHUB_PATH
      shell: sh
